### PR TITLE
Show if buyer has joined area

### PR DESCRIPTION
**Pull request by ldbenoit**
Adds text to buyer's other slot if they join or leave area. In the future it would be nice to have a notification on their tab as well.

### CODE REVIEW

**Comment by lemasato** [comment]
That could be a great improvement.  
Though, I'd like to implement it differently.

**Comment by avgjoe** [comment]
I use a dual monitor set up, with my level 25 trader account in about as small a window as I can get. Sometimes I can't even catch the "player has joined area message." The addition of a sound notification on this would be awesome as well.

**Comment by lemasato** [comment]
Maybe another GUI (docked to Trades GUI) containing tabs id of players that joined the area.
That would be convenient. Not sure... It wouldn't look nice.

**Comment by ldbenoit** [comment]
I worked updated this on my fork today. Added an @ symbol after any tab ID when the buyer joins the area, It also plays the trade sound when a player with a trade enters. It might be nice to have a different sound for players joining. Check out the other pull request.
I also ended up fixing a few bugs that I came across.

**Comment by lemasato** [comment]
Interesting, I like this one.
But you just gave me another idea. The @ symbol could be used when more whispers from the same person have been received, and another symbol would be used for the "Player joined area" notification. Though, I'm not sure. The interface could become bloated...

**Comment by lemasato** [comment]
Implemented with the new skinning system (#61 Tabs Notifications)

**Pull request closed without merging**
