### PR TITLE
Tab Notifications

### PR DESCRIPTION
**Pull request by ldbenoit**
Fixed duplicate detection not working.

### CODE REVIEW

**Comment by ldbenoit** [comment]
I was actually going to have it as a hidden text originally but I wanted it to update any new trade requests if they were already in the area. Now that I think about it, I'm not sure that happens enough to worry about.
I like the idea of having the @ symbol for other text notification but I chose it mostly because it was attention grabbing and didn't feel like clutter. I'll test out some other indicators.

**Comment by ldbenoit** [comment]
Hey, I ended up storing if the buyer has joined on each tab and it works well. I also changed the area symbol to # and added @ beside any with other info. 

Overall I like it but it can get a bit cluttered and causes a bit of flickering from updating the tabs more often. Maybe add another settings panel for tabs and notification customization.

**Comment by lemasato** [comment]
Looking great. I like that you added customisation for these settings.
But I kind of dislike the idea of having two symbols on the same tab.
The @ symbol seems intuitive, it's obviously someone who whispered you after they sent the trading whisper. But adding another symbol for people who are in the area could be confusing (for the user).
I really wish to make this less intrusive, more intuitive...

[Highlighting tabs](autohotkey.com/board/topic/94599-is-there-a-way-to-highlight-an-active-gui-tab/?p=596140) by using `PostMessage, 0x1333` is not an option, it only works with with un-themed tab controls.
The best way I could think of would be re-rewriting the "System" GUI, using the same way as the PoE skin. Would give more control over the tabs, and customisation.

**Comment by ldbenoit** [comment]
I don't think it's that confusing to be honest, as long as the user is informed of what the symbols mean. Right now it only shows one symbol per tab with the joined message taking priority. I think the notifications settings area will help with clarifying, maybe have the joined symbol be disabled by default. However, I find the joined message more useful. Maybe the joined symbol could be '$', meaning the trade is ready?

**Comment by lemasato** [comment]
I'll see how we can implement this once the new GUI is finished.

**Comment by ldbenoit** [comment]
Cool, looking forward to the gui changes.

**Comment by lemasato** [comment]
Okay. So the new skinning system has been released.  
It makes use of [Class_ImageButton](https://github.com/AHK-just-me/Class_ImageButton). It makes using and creating "Image buttons" easier.  
Simple and easy to use: You create a button, then use `ImageButton.Create(handler, IBStyle*)`  
Example:  
`IBStyle_Tab := [ [0, SkinAssets.Tab_Inactive, "", colorTabInactive, "", pngTransColor]`
`, [0, SkinAssets.Tab_Hover, "", colorTabHover, "", pngTransColor]`  
`, [0, SkinAssets.Tab_Press, "", colorTabPress, "", pngTransColor]`  
`, [0, SkinAssets.Tab_Active, "", colorTabActive, "", pngTransColor] ]`
0 mean we are using a bitmap.  
SkinAssets.Tab_Inactive is the image file used.  
colorTabInactive is the color of the button's caption.  
pngTransColor is the color that will replace any transparent pixel (on the .png)  

ID 1 on the array is the default state for the button. ID 2 is when the button is being hovered by the cursor. ID 3 is when it is pressed. ID 4 is when the button is set as "Disabled". We only use it with tabs, as a "defaulted" state.
***
Now, about "Tab Notifications":
How would it work:
Tabs could use another asset with specific colours.. Green for "in area". Purple for "whisper received".
Upon checking a purple tab's "Other Slot", it would turn back to normal.  
Say we have tabs "1 2 3 4 5". Player from 3 joins the area: His tab turns to the green asset.  

How to implement it:  
We can either create three different set of tabs (Default, Green, Purple) and choose which tab of which set to use depending on the tab.

Or edit the tab that needs to be changed by calling ImageButton.Create(TradesGUI_Controls["Tab_" tabID]` then re-creating the button's caption with GuiControl. But in my opinion, the first solution is far better:

- All tabs variant will be pre-existing, we won't need to use `ImageButton.Create()` to edit the tab's assets.
- Fast and reliable, we only make use of `GuiControl, Hide/Show`.

**Comment by ldbenoit** [comment]
Hey, this looks good. Your first method sounds like it would work just fine. One problem I can see is that you would want the tab you have selected also be able to have notifications. That means additional hidden tabs and assets.

I had a look at this today and had some other suggestions. 

I notice you are using separate assets for the arrows, and close buttons. You should remove the <,>, and x text from the buttons and just make them part of the PNG to allow for more customization in skins.

I think if you start adding more colours to the buttons the active tab might not stand out as much. I think having the bottom be a little higher might help. Something like this:

tabactive

I think the grey area of the buttons should be there even if the buttons aren't active. I think it looks a little strange when you only have a few tabs,


I'm really happy with the improvements you've made. If you wanted, I could work on the notifications while I have time before 3.0.

**Comment by lemasato** [comment]
>I notice you are using separate assets for the arrows, and close buttons. You should remove the <,>, and x text from the buttons and just make them part of the PNG to allow for more customization in skins.

The <,>,X symbols can actually be toggled on or off, in Assets.ini: Use_Character=True.  
The PoE skin, for example, has its own .png for these, so I disabled it. I think it just looks better to leave the font draw the symbols with this theme. It's a "simplistic" theme, so it really fits.

> I think if you start adding more colours to the buttons the active tab might not stand out as much. I think having the bottom be a little higher might help. Something like this:

True. The banner could use some change too, so that the top border of the tab can be seen better.

> I think the grey area of the buttons should be there even if the buttons aren't active. I think it looks a little strange when you only have a few tabs,

Actually, I think too... The reason I made it that way is for the PoE skin. But I just realized it could be easily fixed by adding another asset for "Tab Background"

> I'm really happy with the improvements you've made. If you wanted, I could work on the notifications while I have time before 3.0.

It's up to you! You did a pretty good job back there.  
But it's really really up to you. I'm not forcing you into it, so if you do not have the time to work on this, simply let me know.

**Comment by ldbenoit** [comment]
Hey, I worked on this today on a new [fork](https://github.com/ldbenoit/POE-Trades-Helper/tree/1.12_Notifications), take a look and let me know if there's anything I can improve. It is mostly complete but there are some things that still need work.

- The new tabs need assets, right now it only changes font colour  to show it's working.
- Skin should probably have settings for the new tab colours.
- Adding settings for enabling disabling the feature would be nice, as well as adding a separate sound for players joining

Some notes about it's implementation:
- Three notification tabs are created for each tab. Each with their own IBStyle
- The old TradesGUI_Controls["Tab_"{id}] is now TabDefault_{id} and tab_{id} is assigned to whatever notification is active. This seemed like the easiest way to implement without changing your code too much.
- GUI_Trades_Update_Tab_Style(tabId) is ran with every update. It hides the current tab style and assigns the proper style to TradesGUI_Controls["Tab_"{id}] and makes it visible if needed. 
- Uses GUI_Trades_Set_NewMsg(tabId) and GUI_Trades_Set_InArea(tabId) to set the alerts. This could be moved to Gui_Trades_Set_Trades_Infos({tabId:id, NewMsg:1}) if you wanted.

**Comment by lemasato** [comment]
[I commented on your commit here](https://github.com/ldbenoit/POE-Trades-Helper/commit/d9bfe5c20f11ba4bf786d1820f9cb667a483e493#commitcomment-23379321)

> Skin should probably have settings for the new tab colours.

Yep. I plan on adding new assets with green / purple borders.

> Adding settings for enabling disabling the feature would be nice, as well as adding a separate sound for players joining.

I'm not sure if people would want to disable this feature, but having a specific sound effect is a must for sure. But it's okay, I will handle these.

**Comment by ldbenoit** [comment]
> Yep. I plan on adding new assets with green / purple borders.
I actually meant font colours, just to add something else for the skin to customize.

**Comment by lemasato** [comment]
I merged the changes from [1.12_Notifications](https://github.com/ldbenoit/POE-Trades-Helper/tree/1.12_Notifications) to the dev branch [(as well as a few other changes)](https://github.com/lemasato/POE-Trades-Companion/commits/dev).  
Thanks a lot for your work, I really like your take on this!

Also noticed the bugfixes from #62 were part of 1.12_Notifications.
Can I close #62 or is there something I missed?

**Comment by ldbenoit** [comment]
> I merged the changes from 1.12_Notifications to the dev branch (as well as some other changes).
Thanks a lot for your work, I really like your take on this!
Thanks, I'm glad you like it. It's something I found really useful and stopped me from upgrading to your newer versions in the past. I use this tool constantly, great work.

> Also noticed the bugfixes from #62 were part of 1.12_Notifications.
Can I close #62 or is there something I missed?
Go ahead and close, I made that in case you didn't want to pull all of the notification changes you could simply pull the bugfixes.

I had some thoughts on skinning as well. All folders in the ./resources/skins directory should be automatically added. You probably already have thought on that but if not it should be top priority IMO. The assets.ini seems unnecessary, you could shift anything important to settings.ini and just enforce a strict naming scheme on assets, no? I also found the joined asset wasn't as noticeable as the others.

**Comment by lemasato** [comment]
> I had some thoughts on skinning as well. All folders in the ./resources/skins directory should be automatically added. You probably already have thought on that but if not it should be top priority IMO. The assets.ini seems unnecessary, you could shift anything important to settings.ini and just enforce a strict naming scheme on assets, no? I also found the joined asset wasn't as noticeable as the others.

Yeah. I thought of that as soon as I started working on the White skin. Now that all skins require the same amount of assets, it just becomes tedious to #FileInstall them all manually.  
The way I see it, it could be done by looping through the ./resources/skins/ folder and appending #FileInstall (followed by the file location) to an .ahk file then #Include the file.  

To me, Assets.ini is just so handy. 
All assets need to point to an existing .png file for the script to work. 
If someone wishes not to use a specific state for an asset, he can just point it to another .png (Example: Tab_Press uses TabActive.png). This makes working with skins easier in my opinion.

**Comment by ldbenoit** [comment]
Hey, I added auto skin install to my [Dev](https://github.com/ldbenoit/POE-Trades-Helper/commit/d195fdf45b612557d2b2589ba2a90cd46993d488) branch, take a look. It could be expanded to install any files you have but it's probably not necessary.

> All assets need to point to an existing .png file for the script to work.

I figured you could have a few required files like; TabActive, TabInactive. If the skin was missing those it wouldnt register, but if it met the minimum it would default the missing ones. Pressed could be active, joined and whisper would just be inactive.  I suppose I see the benefit of it though.

**Pull request closed without merging**
