### PR TITLE
Add a button to the buyer gui to send a whois query on the seller

### PR DESCRIPTION
**Pull request by tonytamps**
As the title says, just added a whois button to the buyer GUI.

Often when I'm buying something and not getting a response I want to know if they're in lab or a map so I can wait a bit before looking for another item. If this were easier to do (or if more people knew you could do it) I suspect some trade interactions would be a little less hostile.

My editor automatically trimmed meaningless whitespace which makes this change look significantly larger than it actually is.
I can try to undo the whitespace changes if it bothers you or leave them here. Your call.

I also had to create a few icons for this. I'm okay with most of them but really don't like how the "white" theme icons turned out. I'm a very poor designer and assume you've got a better way to create these icons that what I was doing. I just drew them pixel by pixel in MS Paint.

### CODE REVIEW

**Comment by tonytamps** [comment]
I realise now that I should have attached screenshots but I'm at work on a macbook so I'll have to do it when I get home

**Comment by lemasato** [comment]
Hey, quite nice and clean implementation - but https://github.com/lemasato/POE-Trades-Companion/tree/alpha is bringing full Buying interface customization as well as an interface rework, you should check it out. Releases can be downloaded from the #alpha-channel in discord.

**Comment by tonytamps** [comment]
Oh very cool. I struggled a bit figuring our which branch you've been releasing from but got there in the end. Well... got to the branch I was getting releases from at least.

Happy to make the changes in `alpha` too / instead. As long as I can use the feature soonish I'll be happy.

To be honest AHK isn't my strong suit so I'm a little slow.

You mentioned in Discord
> I still would like it to stick to my ideology for this tool

Are you able to verbalise what that is? Can be hard to code to an expectation you don't know.

Thanks @lemasato

**Comment by lemasato** [comment]
Clarification on branches:
- master is old and outdated, don't use it
- dev is the "BETA" branch, used to be the active one for updates
- alpha is the "ALPHA" branch, updates are pushed there now until fully finished
- alpha-new-class-gui is where I'm "currently" changing all the GUI code to the new class

You'd be able to use the /whois feature right away, as the buttons are now customizable - by default it sends a /whois and re-send the whisper message.

My ideology is pretty much "only stick to trading" and "no fully automated behaviours".
GGG old standards say that you *will* get banned for using chat macros that send more than a single message... Because it does more than a single server action per key press. But we all know that will never happen. No one in the entire history of POE has been banned for sending two chat messages at once - because that would be completely stupid of GGG. Same with flask macros, no one will ever get banned for it unless they're blatantly streaming it. Those, in my opinion, are worthy QOL features.
But automating things like the whole trading process, or anything that could be related to botting is a no-go. No automatically sending a trade request when someone joins your hideout, no automatically accepting the trade window if the price requested is right, etc.

**Comment by tonytamps** [comment]
Thanks for that. Makes sense and I completely agree.

The feature I added and then removed would send a whois straight after sending the whisper but knowing GGGs stance on multiple actions and not wanting to put your reputation at risk I removed the functionality before submitting the PR.

I'll take a look at `alpha` and see what's up. Will need run a version of alpha myself first though...

**Comment by tonytamps** [comment]
Okay well going to close this in favour of the alpha branch. Thanks for that.

Let me know if there is anything I can help with otherwise.

**Pull request closed without merging**
